### ISSUE TITLE
Recycling Button Disposition Imagen broken

### ISSUE THREAD

**Issue by jamescr** [labexp/osmtracker-android-layouts#44]
Hi @angoca. Thanks for submitting the Recycling layout. 

In the [README.md file](https://github.com/labexp/osmtracker-android-layouts/blob/master/layouts/recycling/README.md), the image of button disposition is broken.

![imagen](https://user-images.githubusercontent.com/593829/188494998-efa17139-8a78-4613-b338-3bbc3afcd28f.png)

**Comment by angoca** [comment]
Sure, I will take a look. Thank you.

**Comment by angoca** [comment]
Corrected in #47
