### ISSUE TITLE
No icons in Public Transport Layout

### ISSUE THREAD

**Issue by jamescr** [labexp/osmtracker-android-layouts#7]
Icons are downloaded but aren't visible when using Public Transport Layout. The problems seems to be related with the path of every image file.

**Comment by adam3497** [comment]
Are you have the default parameters on your GitHub Repository Settings tab?

**Comment by jamescr** [comment]
I'm using the default settings.

**Comment by adam3497** [comment]
What version of OSMTracker are you using? I was testing with beta version 4 of OSMTracker and everything is ok.
